# Site settings
title: "Gean Ramos"
description: "Seja fiel à sua essência e jamais viva para simplesmente agradar os outros."
# baseurl: "/" # the subpath of your site, e.g. /blog
 url: "http://www.gean.me" # the base hostname & protocol for your site e.g. https://geanramos.com

# User settings
username: Gean Ramos
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_title: Software Engineer
email: contato@geanramos.com
 twitter_username: geanramos
 github_username:  geanramos
 gplus_username:  geanramos

exclude: ['package.json', 'src' , 'node_modules']
